debug: true
help: https://github.com/tpc3/DuckPolice/wiki
discord:
  token: YOUR_TOKEN_HERE
  status: Duck Police is observing you | p.help
db:
  kind: sqlite3
  parameter: ./db.sqlite
  tableprefix: duckpolice_
guild:
  prefix: p.
  lang: japanese
  ignore:
  - "^< "
  alert:
    type: reply
    message: 既出警察だ！
    react: "\U0001F6A8"
    reject: "❌"
  domain:
    mode: white
    list:
    - twitter.com
    - youtube.com
  channel:
    thread: threadId
log_period: 2592000

